[package]
name = "the-bumps"
version = "0.1.0"
authors = ["Matthew Else <matthewelse1997@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
nom = "7.1.3"
